from app.prompts.resume.overall import OVERALL_SYSTEM_PROMPT, OVERALL_USER_PROMPT
from app.prompts.resume.ats import ATS_SYSTEM_PROMPT, ATS_USER_PROMPT
from app.prompts.resume.job_match import JOB_MATCH_SYSTEM_PROMPT, JOB_MATCH_USER_PROMPT
from app.prompts.resume.sections import SECTIONS_SYSTEM_PROMPT, SECTIONS_USER_PROMPT
from app.prompts.resume.strengths import STRENGTHS_SYSTEM_PROMPT, STRENGTHS_USER_PROMPT
from app.prompts.resume.missing import MISSING_SYSTEM_PROMPT, MISSING_USER_PROMPT
from app.prompts.resume.recommendations import (
    RECOMMENDATIONS_SYSTEM_PROMPT,
    RECOMMENDATIONS_USER_PROMPT,
)
from app.prompts.resume.improvements import (
    IMPROVEMENTS_SYSTEM_PROMPT,
    IMPROVEMENTS_USER_PROMPT,
)

__all__ = [
    "OVERALL_SYSTEM_PROMPT",
    "OVERALL_USER_PROMPT",
    "ATS_SYSTEM_PROMPT",
    "ATS_USER_PROMPT",
    "JOB_MATCH_SYSTEM_PROMPT",
    "JOB_MATCH_USER_PROMPT",
    "SECTIONS_SYSTEM_PROMPT",
    "SECTIONS_USER_PROMPT",
    "STRENGTHS_SYSTEM_PROMPT",
    "STRENGTHS_USER_PROMPT",
    "MISSING_SYSTEM_PROMPT",
    "MISSING_USER_PROMPT",
    "RECOMMENDATIONS_SYSTEM_PROMPT",
    "RECOMMENDATIONS_USER_PROMPT",
    "IMPROVEMENTS_SYSTEM_PROMPT",
    "IMPROVEMENTS_USER_PROMPT",
]
